-- ============================================================
-- FraudGuard Chrome Extension — Database Migration
-- Run this in the Supabase SQL editor (project dashboard).
-- ============================================================

-- 1. extension_tokens table
-- Stores short-lived tokens generated by HR for each candidate session.

CREATE TABLE IF NOT EXISTS public.extension_tokens (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token         TEXT NOT NULL UNIQUE,             -- 8-char uppercase code
  session_id    UUID NOT NULL REFERENCES public._interview_sessions(id) ON DELETE CASCADE,
  candidate_email TEXT NOT NULL,
  company_id    TEXT NOT NULL,
  expires_at    TIMESTAMPTZ NOT NULL,
  used          BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_extension_tokens_token     ON public.extension_tokens(token);
CREATE INDEX IF NOT EXISTS idx_extension_tokens_session   ON public.extension_tokens(session_id);
CREATE INDEX IF NOT EXISTS idx_extension_tokens_company   ON public.extension_tokens(company_id);

-- 2. Add gambling_analysis and proctoring_data columns to _interview_sessions
-- (no-op if columns already exist — safe to re-run)

ALTER TABLE public._interview_sessions
  ADD COLUMN IF NOT EXISTS gambling_analysis JSONB,
  ADD COLUMN IF NOT EXISTS proctoring_data   JSONB;

-- 3. RLS policies for extension_tokens

ALTER TABLE public.extension_tokens ENABLE ROW LEVEL SECURITY;

-- Authenticated recruiters can manage tokens for their company
CREATE POLICY "extension_tokens_select_company" ON public.extension_tokens
  FOR SELECT TO authenticated
  USING (
    company_id = (
      SELECT company_id FROM public._users WHERE id = auth.uid() LIMIT 1
    )
    OR (
      SELECT role FROM public._users WHERE id = auth.uid() LIMIT 1
    ) = 'System Admin'
  );

CREATE POLICY "extension_tokens_insert_company" ON public.extension_tokens
  FOR INSERT TO authenticated
  WITH CHECK (
    company_id = (
      SELECT company_id FROM public._users WHERE id = auth.uid() LIMIT 1
    )
    OR (
      SELECT role FROM public._users WHERE id = auth.uid() LIMIT 1
    ) = 'System Admin'
  );

-- No direct UPDATE/DELETE from client — service role only (via API server)
